### ISSUE TITLE
Allow user to specify full path to MSBuild exe in config

### ISSUE THREAD

**Issue by stevewillcock** [stevewillcock/grunt-msbuild#12]
For build servers, and to generally enhance flexibility

**Comment by phillip-haydon** [comment]
Any update on this? Can't build .NET 4.6 :/

**Comment by stevewillcock** [comment]
This works fine for me against .NET 4.6 projects, what problem are you seeing?

Make sure to specify version 14 in the gruntfile (or just omit the version and it should use 14 by default)

Thanks

Steve

**Comment by phillip-haydon** [comment]
Hey @stevewillcock sorry for late response, had urgent flight to go to funeral. 

The problem turns out to be, because you cannot build Azure Projects in Team City without installing Visual Studio...

After installing VS 2015 Community edition. The build works fine. 

So frustrating!

**Comment by stevewillcock** [comment]
Hi @phillip-haydon, no problem at all, and sorry to hear that.

Thanks for the clarification - you're right, that limitation for building Azure projects certainly does seem frustrating.
