### ISSUE TITLE
Issues in mixed VS version enivronments

### ISSUE THREAD

**Issue by tomfulton** [stevewillcock/grunt-msbuild#14]
We've got some developers using VS12 and some VS13.  This seems to cause some issues as grunt-msbuild only handles one MSBuild path.

I'm unsure what the proper solution is, but I took a stab at a possible fix here:  https://github.com/stevewillcock/grunt-msbuild/pull/13

**Comment by stevewillcock** [comment]
Closing this as the recent fix from @whyleee adds multiple version support
