### ISSUE TITLE
Specify .Net Version 4.5.2

### ISSUE THREAD

**Issue by rickj33** [stevewillcock/grunt-msbuild#29]
Trying to use the version option to specify to compile on 4.5.2, but that value is not accepted as a valid number. What is the correct way to compile using 4.5.2

**Comment by rickj33** [comment]
I figured it out, specify the version as 12, will use the msbuild for vs2013 to compile, and the project files specify the .net version to use.

**Comment by stevewillcock** [comment]
Great, glad you sorted it out.

**Comment by jmbeach** [comment]
This doesn't always work for website projects

**Comment by jmbeach** [comment]
I am wrong. Please ignore.
