### ISSUE TITLE
Custom msbuild version fallback

### ISSUE THREAD

**Issue by arthrp** [stevewillcock/grunt-msbuild#32]
Would be really good to have an ability to specify a custom fallback version. There is a common scenario when different people in team use different tools (e.g. different versions of VS).

**Comment by stevewillcock** [comment]
Sounds like a nice feature, I can see how that might be an issue in many teams.

**Comment by stevewillcock** [comment]
This can be achieved in the latest version (1.0.1) by putting msbuild in the path and using "msbuild" (for example) as the msbuildPath options parameter
