### ISSUE TITLE
Allow using 32-bit MSBuild from VS 2017

### ISSUE THREAD

**Issue by msjogren** [stevewillcock/grunt-msbuild#41]
I'm updating a UWP app from VS 2015 to 2017, and in the process I started getting the same build errors mentioned in this thread when building on a Jenkins server and using grunt.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/23c8df57-9c50-476c-9f56-1fe058e75a9d/uwp-app-builds-on-local-machine-fails-on-build-agent-systemprivatecorelib-not-found

First of many compile errors:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1251,5): error MSB3816: Loading assembly "f:\j\workspace\MyApp\buildfolder\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\runtimes\aot\lib\netcore50\mscorlib.dll" failed. System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [f:\j\workspace\MyApp\buildfolder\MyProject\MyProject.csproj]

And as it says in the answer to that forum thread, the solution is to use the 32-bit version of MSBuild and not the 64-bit. I've verified that the build completes successfully if I change this. That's also recommended at the end of this page.

https://msdn.microsoft.com/en-us/library/dn600634(v=vs.110).aspx

Unfortunately grunt-msbuild is currently hardcoded to use the amd64 version in inferMSBuildPathViaVSWhere when building with VS 2017. It would be great if you could make this configurable, using options.processor that is used elsewhere.

**Comment by stevewillcock** [comment]
Thanks for the issue log - sounds like a good idea, I'll look into it :)

**Comment by stevewillcock** [comment]
This is resolved in the new version where an explicit path to msbuild is used
