### ISSUE TITLE
Visual Studio 2019 puts MSBuild in yet another folder

### ISSUE THREAD

**Issue by anthonydotnet** [stevewillcock/grunt-msbuild#45]
The new folder is this:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\MSBuild.exe

Your string building uses a version number when constructing the path. I did try to modify it myself however, I think the logic needs to be significantly changed due to a combination of vswhere.exe output, and the quirky version folders in general.

Would you accept a pull request which just allows the dev to pass the full msbuild path?

`msbuild: {
			dev: {
				src: [projectDir + pkg.name + '.csproj'],
				options: {
					msbuildPath: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\amd64\\MSBuild.exe',
					projectConfiguration: 'Release',
					targets: ['Clean', 'Rebuild'],
					buildParameters: {
						PostBuildEvent: ''
					}
				}
			}
		},
`

Then createCommand becomes :

` function createCommand(options) {
		if (options.msbuildPath != undefined){
			return options.msbuildPath;	
		}
...

`

**Comment by anthonydotnet** [comment]
Sorry about the fomatting... not sure how to make it nicer :(

**Comment by stevewillcock** [comment]
Yes, that would be great, sounds like a good solution to the ever changing msbuild path issue :)

**Comment by anthonydotnet** [comment]
Great. I'll have it over to you by Saturday.

**Comment by stevewillcock** [comment]
Thanks for the PR on this - I'm just going to do some testing locally here and then I'll push a new version to npm

**Comment by anthonydotnet** [comment]
Cool. I took the liberty of updating the docs too. I assumed that this would be v3.0 as it is a breaking change.

**Comment by stevewillcock** [comment]
Definitely a v3.0, and thanks for the docs update :)

**Comment by stevewillcock** [comment]
Hi, published to npm - the previous version was 0.4.6 so I actually published this as 1.0.0 as it's a breaking change as you mentioned. I added a check to see if the option was set and another to check if the file exists. I also updated the async dependency as that was way out of date. Please let me know if you have any issues with this new version.

**Comment by stevewillcock** [comment]
Published another version (1.0.1) where I removed the file check as I couldn't do a cross platform build on Windows and MacOS - not doing the file check allows, for example, someone to set the build path as 'msbuild' which supports cross platform build scenarios

**Comment by anthonydotnet** [comment]
I forgot to mention that I was a bit confused. 

I thought the version in package.son was out of date but didnt want to touch it and was going to ask you about it....It has a much lower number than in your release notes (bottom of readme). Unless I'm missing something shouldnt these numbers be the same?

**Comment by stevewillcock** [comment]
Yes, at some point the 0.2.0 version ended up as 2.0.0 in the release notes
- I’ve updated the release notes now

**Comment by anthonydotnet** [comment]
Cool. Now I understand. 

I'm personally totally bad with release notes. Like all devs, I'm lazy when it comes to reading and writing documentation. My code is self documenting :)

**Comment by anthonydotnet** [comment]
Confirming that I have testing this release.

Works! Woot!

**Comment by stevewillcock** [comment]
Awesome, thanks for that, I’ll close this issue now then :)
