### ISSUE TITLE
VS 2017 & VS build tools 2019 installed but vswhere is just finding VS2019s msbuild for a VS2017 project

### ISSUE THREAD

**Issue by MarkusDeutschmann** [stevewillcock/grunt-msbuild#51]
I my environment I have Visual Studio Professional 2017 (15.9.28307.1321) and the Visual Studio Build Tools 2019 (16.8.30804.86) installed. 
The configuration is as follow: 
```json
...
msbuild: {
			MyProject: {
				src: "src/MyProject.sln",
				options: {
					projectConfiguration: "Release",
					platform: "Win32",
					targets: ["Rebuild"],
					maxCpuCount: 2,
					verbosity: "quiet",
					inferMsbuildPath: true
				}
			}
		},
...
```
The problem is the automatic detection of the MSBuildPath via inferMsbuildPath does not work.
The used vswhere is called with the following parameters:
```shell
-latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\\**\\MSBuild.exe`
```
the result is:
```shell
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
```

When I remove the `-latest` I got all msbuild paths but the unneeded one are on top and the grunt_msbuild is taking always  the first one:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\MSBuild.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe
```
So I was thinking the adding of `-version [15.0,16.0)` should work and that is exactly the case. 
Also just setting the `-products` option from `*` to 
```-products Microsoft.VisualStudio.Product.Professional```
will lead to the correct result.

I think useful would be here to add one or two new options to be able to stear that misleading selection of the buildpath via vswhere.exe.
Maybe a new option like vswhereOptionVersion and vswhereOptionProduct could be added:
```json
...
msbuild: {
			MyProject: {
				src: "src/MyProject.sln",
				options: {
					projectConfiguration: "Release",
					platform: "Win32",
					targets: ["Rebuild"],
					maxCpuCount: 2,
					verbosity: "quiet",
					inferMsbuildPath: true,
                                        vswhereOptionVersion: "[15.0,16.0)",
                                        vswhereOptionProduct: "Microsoft.VisualStudio.Product.Professional"
				}
			}
		},
...
```

What do you think, would you allow a pull request that allow the setting/overwriting of the two vswhere.exe options in the described way?

**Comment by stevewillcock** [comment]
Hi Markus,

Thanks for taking the time to send this over. Yes, those seem like they would be good additions for the options, I'd be happy to merge a PR which added those in.

Thanks again

Steve

**Comment by MarkusDeutschmann** [comment]
Ok will do.
Sorry but I have tow additional questions: 
1. In the README there are the options: 
   - failOnError
   - visualStudioVersion
   - platform
   - nologo
   missing. Should that be added to the README?
2. The currently used vswhere.exe version is the version 2.6.7. According to https://github.com/microsoft/vswhere/releases the latest version is the 2.8.4. Do you think it makes sence to update that?

If you agree also updating that should that also be part of that pull request then?

**Comment by stevewillcock** [comment]
Hi Markus,

Great, thanks.

To answer your questions:

1. You're right, it looks like those should be added to the README.
2. Yes, I think that using the latest version makes sense if possible.

If you were happy to include those in a PR that would be brilliant, or if you think they should be separate PR's that's good too - whatever works for you if you were interested in doing these.

Steve

**Comment by MarkusDeutschmann** [comment]
Hi Steve,

ok, thanks. I put all changes in this PR: https://github.com/stevewillcock/grunt-msbuild/pull/52

Markus

**Comment by stevewillcock** [comment]
PR merged, thanks! Will release asap

**Comment by stevewillcock** [comment]
Reeased as 1.3.1 https://www.npmjs.com/package/grunt-msbuild - sorry for the delay, things got away from me a bit there!
